-- ==============================================================================
-- SKEMA DATABASE SUPABASE UNTUK YAYASAN MODERN AL-ALAWIYAH
-- Project Ref: rqvecsfaqmxfnivaomjf
-- Jalankan skrip ini di SQL Editor di Dashboard Supabase:
-- https://supabase.com/dashboard/project/rqvecsfaqmxfnivaomjf/sql
-- ==============================================================================

-- 1. Tabel Informasi Sekolah (site_info)
CREATE TABLE IF NOT EXISTS public.site_info (
    id BIGINT PRIMARY KEY DEFAULT 1,
    "schoolName" TEXT NOT NULL DEFAULT 'Yayasan Modern Al-Alawiyah',
    slogan TEXT DEFAULT 'Membentuk Generasi Berakhlak Mulia, Cerdas, dan Berprestasi',
    address TEXT DEFAULT 'Jl. KH Muhidin Kp.Bubulak Santri No.Rt03/04, Kencana, Tanah Sareal, Kota Bogor, Jawa Barat 16161',
    phone TEXT DEFAULT '+62 251 123 456',
    email TEXT DEFAULT 'info@alalawiyah.sch.id',
    whatsapp TEXT DEFAULT '6281234567890',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Staff & Pengajar (staff)
CREATE TABLE IF NOT EXISTS public.staff (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama TEXT NOT NULL,
    jabatan TEXT NOT NULL,
    gambar TEXT,
    deskripsi TEXT
);

-- 3. Tabel Galeri Foto (galeri)
CREATE TABLE IF NOT EXISTS public.galeri (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    gambar TEXT NOT NULL,
    judul TEXT NOT NULL,
    kategori TEXT DEFAULT 'kegiatan'
);

-- 4. Tabel Hero Banner Slider (hero_images)
CREATE TABLE IF NOT EXISTS public.hero_images (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    gambar TEXT NOT NULL,
    judul TEXT NOT NULL
);

-- 5. Tabel Program Pendidikan Utama (programs)
CREATE TABLE IF NOT EXISTS public.programs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama TEXT NOT NULL,
    deskripsi TEXT,
    gambar TEXT
);

-- 6. Tabel Jurusan SMK (jurusan)
CREATE TABLE IF NOT EXISTS public.jurusan (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    deskripsi TEXT,
    karir TEXT,
    gambar TEXT,
    aksi BOOLEAN DEFAULT true
);

-- 7. Tabel Pendaftaran PPDB Siswa Baru (ppdb_pendaftaran)
CREATE TABLE IF NOT EXISTS public.ppdb_pendaftaran (
    id BIGINT PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    "nomorRegistrasi" TEXT,
    "namaCalonSiswa" TEXT NOT NULL,
    "namaOrangTua" TEXT NOT NULL,
    telepon TEXT NOT NULL,
    email TEXT,
    jenjang TEXT NOT NULL DEFAULT 'SMP/MTs',
    jurusan TEXT,
    "jenisKelamin" TEXT DEFAULT 'Laki-laki',
    "asalSekolah" TEXT,
    "pilihanAsrama" TEXT DEFAULT 'Boarding (Asrama)',
    "jalurPendaftaran" TEXT DEFAULT 'Reguler',
    gelombang TEXT DEFAULT 'Gelombang 1',
    alamat TEXT,
    status TEXT DEFAULT 'Menunggu Verifikasi',
    "catatanAdmin" TEXT
);

-- 8. Tabel Pesan Masuk Pengunjung (pesan_kontak)
CREATE TABLE IF NOT EXISTS public.pesan_kontak (
    id BIGINT PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    nama TEXT NOT NULL,
    email TEXT,
    telepon TEXT,
    pesan TEXT NOT NULL,
    status TEXT DEFAULT 'unread'
);

-- ==============================================================================
-- KEAMANAN / ROW LEVEL SECURITY (RLS)
-- ==============================================================================

ALTER TABLE public.site_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.galeri ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hero_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jurusan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ppdb_pendaftaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pesan_kontak ENABLE ROW LEVEL SECURITY;

-- Kebijakan Baca Publik (Semua orang bisa melihat info sekolah, staff, galeri, dll)
CREATE POLICY "Public Read site_info" ON public.site_info FOR SELECT USING (true);
CREATE POLICY "Public Read staff" ON public.staff FOR SELECT USING (true);
CREATE POLICY "Public Read galeri" ON public.galeri FOR SELECT USING (true);
CREATE POLICY "Public Read hero_images" ON public.hero_images FOR SELECT USING (true);
CREATE POLICY "Public Read programs" ON public.programs FOR SELECT USING (true);
CREATE POLICY "Public Read jurusan" ON public.jurusan FOR SELECT USING (true);

-- Kebijakan Kirim Publik (Calon murid / pengunjung bisa mendaftar PPDB & kirim pesan)
CREATE POLICY "Public Insert ppdb_pendaftaran" ON public.ppdb_pendaftaran FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Read ppdb_pendaftaran" ON public.ppdb_pendaftaran FOR SELECT USING (true);
CREATE POLICY "Public Update ppdb_pendaftaran" ON public.ppdb_pendaftaran FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Public Delete ppdb_pendaftaran" ON public.ppdb_pendaftaran FOR DELETE USING (true);

CREATE POLICY "Public Insert pesan_kontak" ON public.pesan_kontak FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Read pesan_kontak" ON public.pesan_kontak FOR SELECT USING (true);
CREATE POLICY "Public Delete pesan_kontak" ON public.pesan_kontak FOR DELETE USING (true);

-- Kebijakan Kelola Data Konten (Untuk admin & service_role)
CREATE POLICY "Admin All site_info" ON public.site_info FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin All staff" ON public.staff FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin All galeri" ON public.galeri FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin All hero_images" ON public.hero_images FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin All programs" ON public.programs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin All jurusan" ON public.jurusan FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- INITIAL SEED DATA (DATA AWAL)
-- ==============================================================================

INSERT INTO public.site_info (id, "schoolName", slogan, address, phone, email, whatsapp)
VALUES (
    1,
    'Yayasan Modern Al-Alawiyah',
    'Membentuk Generasi Berakhlak Mulia, Cerdas, dan Berprestasi',
    'Jl. KH Muhidin Kp.Bubulak Santri No.Rt03/04, Kencana, Tanah Sareal, Kota Bogor, Jawa Barat 16161',
    '+62 251 123 456',
    'info@alalawiyah.sch.id',
    '6281234567890'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.staff (id, nama, jabatan, gambar, deskripsi) VALUES
(1, 'H. Ahmad Fauzi, S.Pd.I, M.Pd', 'Ketua Yayasan', '/images/staff-1.jpg', 'Pendiri & Penanggung Jawab Utama Yayasan Modern Al-Alawiyah'),
(2, 'Dr. Hj. Siti Aminah, M.Pd', 'Kepala Sekolah SMP/MTs', '/images/staff-2.jpg', 'Memimpin jenjang SMP/MTs dengan visi pendidikan Islami terpadu'),
(3, 'Ustadz Muhammad Rizki, Lc', 'Kepala Sekolah SMK', '/images/staff-3.jpg', 'Memimpin jenjang SMK & pengampu bidang kurikulum pesantren'),
(4, 'Ustadzah Nurul Huda, S.Ag', 'Wakil Kepala & Kesiswaan', '/images/staff-4.jpg', 'Membina karakter, pembentukan akhlak, dan prestasi siswa')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.galeri (id, gambar, judul, kategori) VALUES
(1, '/images/galeri-1.jpg', 'Gedung Utama', 'fasilitas'),
(2, '/images/galeri-2.jpg', 'Masjid', 'fasilitas'),
(3, '/images/galeri-3.jpg', 'Ruang Kelas', 'fasilitas'),
(4, '/images/galeri-4.jpg', 'Kegiatan Belajar', 'kegiatan'),
(5, '/images/galeri-5.jpg', 'Wisuda Tahfidz', 'acara'),
(6, '/images/galeri-6.jpg', 'Ekstrakurikuler Hadroh', 'kegiatan')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.hero_images (id, gambar, judul) VALUES
(1, '/images/hero-1.jpg', 'Selamat Datang di Al-Alawiyah'),
(2, '/images/hero-2.jpg', 'Lingkungan Belajar Islami'),
(3, '/images/hero-3.jpg', 'Raih Prestasi, Raih Ridho')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.programs (id, nama, deskripsi, gambar) VALUES
(1, 'SMP/MTs', 'Pendidikan menengah pertama dengan kurikulum nasional dan agama', '/images/program-smp.jpg'),
(2, 'SMK', 'Pendidikan menengah kejuruan dengan berbagai pilihan kompetensi keahlian', '/images/program-smk.jpg'),
(3, 'Pesantren', 'Sistem boarding school dengan pembinaan 24 jam', '/images/program-pesantren.jpg')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.jurusan (id, kode, nama, deskripsi, karir, gambar, aksi) VALUES
(1, 'TKJ', 'Teknik Komputer dan Jaringan', 'Membekali siswa dengan kompetensi merakit, mengelola jaringan, dan administrasi server berbasis Linux & Windows.', 'Junior Network Engineer, IT Support, System Administrator, Technopreneur', '/images/galeri-1.jpg', true),
(2, 'RPL', 'Rekayasa Perangkat Lunak', 'Fokus pada pengembangan aplikasi web, mobile, dan basis data dengan metodologi industri dan praktik kerja lapangan.', 'Web Developer, Mobile Developer, QA Engineer, Backend Developer', '/images/galeri-3.jpg', true),
(3, 'MM', 'Multimedia', 'Melatih keterampilan desain grafis, videografi, animasi 2D/3D, dan fotografi untuk industri kreatif digital.', 'Desainer Grafis, Videografer, Animator, Content Creator', '/images/galeri-4.jpg', true),
(4, 'AKL', 'Akuntansi dan Keuangan Lembaga', 'Menyiapkan tenaga ahli di bidang pembukuan, perpajakan, dan administrasi keuangan lembaga sesuai standar industri.', 'Staf Akuntan, Kasir, Admin Keuangan, Tax Associate', '/images/galeri-2.jpg', false),
(5, 'OTP', 'Otomatisasi dan Tata Kelola Perkantoran', 'Membentuk tenaga administrasi profesional yang menguasai korespondensi, kearsipan, dan aplikasi perkantoran modern.', 'Sekretaris, Office Administrator, Staff HR, Receptionist', '/images/galeri-6.jpg', false),
(6, 'BDP', 'Bisnis Daring dan Pemasaran', 'Pemasaran digital, e-commerce, dan manajemen ritel untuk mencetak wirausahawan muda berjiwa Islami.', 'Digital Marketer, E-commerce Manager, Wirausahawan, Sales Executive', '/images/galeri-5.jpg', false)
ON CONFLICT (id) DO NOTHING;
